### ISSUE TITLE
amqHelper didn't survive a full broker restart?

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/ligmos#2]
Not sure what happened on my end; planned a broker restart and it looks like it noticed it, but didn't actually get packets flowing again even though it said the subscriptions occurred.

Check 2018-07-05 or 2018-07-06 logs for weirdness.

**Comment by astrobokonon** [comment]
Note: activemq server now running again on my office desktop for further testing. Thinking that it could be one of those things where if I had waited a little longer it would have realized it wasn't valid and would have restarted the connections?

**Comment by astrobokonon** [comment]
Relevant log file snippet; looks like it lingered thru many cycles of connection checking before I manually caught it.

```
2018-07-05 17:28:33,396 INFO     Connection died! Reestablishing...
2018-07-05 17:28:33,396 INFO     Connecting to joe.lowell.edu
2018-07-05 17:28:33,401 INFO     Subscribing to joeDevenyOffset
2018-07-05 17:28:33,401 INFO     Subscribing to AOS.AOSSubDataSV.AbsoluteFocusOffset
2018-07-05 17:28:33,401 INFO     Subscribing to DCS.DSSPubDataSV.PositionStatus
2018-07-05 17:28:33,401 INFO     Subscribing to TCS.TCSSharedVariables.TCSHighLevelStatusSV.TCSTcsStatusSV
2018-07-05 17:28:33,402 INFO     Subscribing to TCS.TCSSharedVariables.TCSLowLevelStatusSV.TCSTcsCommandResponseSV
2018-07-05 17:28:33,402 INFO     Subscribing to WFS.WFSPubDataSV.WavefrontData
2018-07-05 17:28:33,402 INFO     Subscribing to AOS.AOSPubDataSV.AOSDataPacket
2018-07-05 17:28:33,402 INFO     Subscribing to DCS.CLSPubDataSV.LowBankState
2018-07-05 17:28:33,402 INFO     Subscribing to DCS.DCSPubDataSV.MountDomeAzimuthDifference
2018-07-05 17:28:33,402 INFO     Subscribing to DCS.DCSPubDataSV.OccultationWarning
2018-07-05 17:28:33,402 INFO     Subscribing to guiderChartInfo
2018-07-05 17:28:33,402 INFO     Starting a big sleep
2018-07-05 17:38:34,034 INFO     Connection still valid
2018-07-05 17:38:34,034 INFO     Starting a big sleep
2018-07-05 17:48:34,660 INFO     Connection still valid
2018-07-05 17:48:34,660 INFO     Starting a big sleep
2018-07-05 17:58:35,286 INFO     Connection still valid
2018-07-05 17:58:35,286 INFO     Starting a big sleep
2018-07-05 18:08:35,908 INFO     Connection still valid
2018-07-05 18:08:35,908 INFO     Starting a big sleep
2018-07-05 18:18:36,534 INFO     Connection still valid
2018-07-05 18:18:36,534 INFO     Starting a big sleep
2018-07-05 18:22:04,770 INFO     Got SIGINT; stopping...
2018-07-05 18:22:05,751 INFO     PID 14251 is now out of here!
2018-07-05 18:22:05,757 INFO     Disconnected from joe.lowell.edu
2018-07-05 18:22:08,641 INFO     Found the following instruments in the configuration file:
2018-07-05 18:22:08,641 INFO     activemq
2018-07-05 18:22:08,642 INFO     Attempting to assign the configuration parameters...
2018-07-05 18:22:08,642 INFO     Applying 'activemq' section of conf. file...
2018-07-05 18:22:08,642 INFO     	name = DCTActiveMQ (<class 'str'>)
2018-07-05 18:22:08,642 INFO     	host = joe.lowell.edu (<class 'str'>)
2018-07-05 18:22:08,642 INFO     	port = 61613 (<class 'str'>)
2018-07-05 18:22:08,642 INFO     	user = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	srcdir = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	destdir = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	dirmask = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	filemask = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	procmon = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	type = ActiveMQ (<class 'str'>)
2018-07-05 18:22:08,642 INFO     	topics = ['joeDevenyOffset', 'AOS.AOSSubDataSV.AbsoluteFocusOffset', 'DCS.DSSPubDataSV.PositionStatus', 'TCS.TCSSharedVariables.TCSHighLevelStatusSV.TCSTcsStatusSV', 'TCS.TCSSharedVariables.TCSLowLevelStatusSV.TCSTcsCommandResponseSV', 'WFS.WFSPubDataSV.WavefrontData', 'AOS.AOSPubDataSV.AOSDataPacket', 'DCS.CLSPubDataSV.LowBankState', 'DCS.DCSPubDataSV.MountDomeAzimuthDifference', 'DCS.DCSPubDataSV.OccultationWarning', 'guiderChartInfo'] (<class 'list'>)
2018-07-05 18:22:08,642 INFO     	influxdbname = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	enabled = True (<class 'bool'>)
2018-07-05 18:22:08,642 INFO     	engEnabled = None (<class 'NoneType'>)
2018-07-05 18:22:08,642 INFO     	running = False (<class 'bool'>)
2018-07-05 18:22:08,642 INFO     	timeout = 60 (<class 'int'>)
2018-07-05 18:22:08,643 INFO     Found the following usernames in the password file:
2018-07-05 18:22:08,643 INFO     yvette wadsworth
2018-07-05 18:22:08,643 INFO     Username None has no password!
2018-07-05 18:22:08,643 INFO     Current PID: 18994
2018-07-05 18:22:08,643 INFO     PID 18994 recorded at /tmp/iago.pid now starting...
2018-07-05 18:22:08,643 INFO     Beginning to monitor the following hosts:
2018-07-05 18:22:08,643 INFO     DCTActiveMQ
2018-07-05 18:22:08,643 INFO     Starting the infinite loop.
2018-07-05 18:22:08,643 INFO     Kill PID 18994 to stop it.
2018-07-05 18:22:08,643 INFO     Connecting to joe.lowell.edu
2018-07-05 18:22:08,647 INFO     Subscribing to joeDevenyOffset
2018-07-05 18:22:08,648 INFO     Subscribing to AOS.AOSSubDataSV.AbsoluteFocusOffset
2018-07-05 18:22:08,648 INFO     Subscribing to DCS.DSSPubDataSV.PositionStatus
2018-07-05 18:22:08,648 INFO     Subscribing to TCS.TCSSharedVariables.TCSHighLevelStatusSV.TCSTcsStatusSV
2018-07-05 18:22:08,648 INFO     Subscribing to TCS.TCSSharedVariables.TCSLowLevelStatusSV.TCSTcsCommandResponseSV
2018-07-05 18:22:08,648 INFO     Subscribing to WFS.WFSPubDataSV.WavefrontData
2018-07-05 18:22:08,648 INFO     Subscribing to AOS.AOSPubDataSV.AOSDataPacket
2018-07-05 18:22:08,648 INFO     Subscribing to DCS.CLSPubDataSV.LowBankState
2018-07-05 18:22:08,648 INFO     Subscribing to DCS.DCSPubDataSV.MountDomeAzimuthDifference
2018-07-05 18:22:08,649 INFO     Subscribing to DCS.DCSPubDataSV.OccultationWarning
2018-07-05 18:22:08,649 INFO     Subscribing to guiderChartInfo
2018-07-05 18:22:08,649 INFO     Connection still valid
2018-07-05 18:22:08,649 INFO     Starting a big sleep
2018-07-05 18:22:09,590 INFO     {'expires': '1530840139593', 'destination': '/topic/TCS.TCSSharedVariables.TCSHighLevelStatusSV.TCSTcsStatusSV', 'subscription': '8675312', 'priority': '4', 'message-id': '454e47f1-8b0c-c707-8a78-452e17054c8d:0:0:2168', 'persistent': 'true', 'timestamp': '1530840129593'}
2018-07-05 18:22:09,590 INFO     <tcsTCSStatus>
  <accessMode>Operator</accessMode>
  <azCurrentWrap>-1</azCurrentWrap>
  <heartbeat>2179</heartbeat>
  <inPositionIsTrue>false</inPositionIsTrue>
  <m1CoverState>Closed</m1CoverState>
  <mountGuideMode>NoTrack</mountGuideMode>
  <rotCurrentWrap>1</rotCurrentWrap>
  <tcsHealth>GOOD</tcsHealth>
  <tcsState>ENABLED</tcsState>
  <currentTimes>
    <lst>
      <hours>12</hours>
      <minutesTime>52</minutesTime>
      <secondsTime>24</secondsTime>
    </lst>
    <time>2018-07-06T01:22:09.504+00:00</time>
  </currentTimes>
  <limits>
    <moonProximity>
      <distance_deg>-1</distance_deg>
      <proximityFlag>false</proximityFlag>
    </moonProximity>
    <sunProximity>
      <distance_deg>-1</distance_deg>
      <proximityFlag>false</proximityFlag>
    </sunProximity>
    <zenith>
      <currentZD_deg>0.00012099999999499</currentZD_deg>
      <elZenithLimit_deg>89.3</elZenithLimit_deg>
      <inBlindSpotIsTrue>false</inBlindSpotIsTrue>
      <timeToBlindSpot_min>1400</timeToBlindSpot_min>
      <timeToBlindSpotExit_min>-1</timeToBlindSpotExit_min>
    </zenith>
    <airmass>1.0000000000022</airmass>
    <currentTimeToObservable_min>-1</currentTimeToObservable_min>
    <currentTimeToUnobservable_min>406</currentTimeToUnobservable_min>
    <timeToRotLimit_min>-1</timeToRotLimit_min>
    <timeToAzLimit_min>-1</timeToAzLimit_min>
  </limits>
  <pointingPositions>
    <azElError>
      <azError>0.0036</azError>
      <elError>0.0252</elError>
    </azElError>
    <currentAzEl>
      <azimuth>
        <degreesArc>173</degreesArc>
        <minutesArc>41</minutesArc>
        <secondsArc>47.9</secondsArc>
      </azimuth>
      <elevation>
        <degreesAlt>89</degreesAlt>
        <minutesArc>59</minutesArc>
        <secondsArc>59.6</secondsArc>
      </elevation>
    </currentAzEl>
    <currentHA>
      <hours>0</hours>
      <minutesTime>0</minutesTime>
      <secondsTime>12.12</secondsTime>
    </currentHA>
    <currentRADec>
      <declination>
        <degreesDec>34</degreesDec>
        <minutesArc>42</minutesArc>
        <secondsArc>20</secondsArc>
      </declination>
      <equinoxPrefix>J</equinoxPrefix>
      <equinoxYear>2000</equinoxYear>
      <frame>FK5</frame>
      <ra>
        <hours>12</hours>
        <minutesTime>51</minutesTime>
        <secondsTime>19.71</secondsTime>
      </ra>
    </currentRADec>
    <currentRotatorPositions>
      <rotPA>179.993874</rotPA>
      <iaa>5</iaa>
      <rotIPA>0</rotIPA>
    </currentRotatorPositions>
    <demandAzEl>
      <azimuth>
        <degreesArc>173</degreesArc>
        <minutesArc>41</minutesArc>
        <secondsArc>48.25</secondsArc>
      </azimuth>
      <elevation>
        <degreesAlt>89</degreesAlt>
        <minutesArc>59</minutesArc>
        <secondsArc>59.87</secondsArc>
      </elevation>
    </demandAzEl>
    <demandRADec>
      <declination>
        <degreesDec>34</degreesDec>
        <minutesArc>43</minutesArc>
        <secondsArc>29.5</secondsArc>
      </declination>
      <equinoxPrefix>J</equinoxPrefix>
      <equinoxYear>2000</equinoxYear>
      <frame>FK5</frame>
      <ra>
        <hours>12</hours>
        <minutesTime>14</minutesTime>
        <secondsTime>58.19</secondsTime>
      </ra>
    </demandRADec>
    <demandRotatorPositions>
      <rotPA>88.907486</rotPA>
    </demandRotatorPositions>
    <targetName>unspecified</targetName>
    <currentParAngle>64.881014719853</currentParAngle>
  </pointingPositions>
  <axesTrackMode>All</axesTrackMode>
  <inPositionAzIsTrue>false</inPositionAzIsTrue>
  <inPositionElIsTrue>false</inPositionElIsTrue>
  <inPositionRotIsTrue>false</inPositionRotIsTrue>
  <externalTargetCfgCmdPreviewIsTrue>false</externalTargetCfgCmdPreviewIsTrue>
  <OffsetStatus>
    <offsetType>SIMPLE</offsetType>
    <userOff1>0</userOff1>
    <userOff2>0</userOff2>
    <handsetOff1>0</handsetOff1>
    <handsetOff2>0</handsetOff2>
  </OffsetStatus>
</tcsTCSStatus>
```

**Comment by astrobokonon** [comment]
In the applied logic portion (say, in https://github.com/LowellObservatory/DataServants/blob/master/Iago.py) the re-connection conditions  originally just called .connect() without specifying a listener!  That means that the packets were received, but never really acted upon by Iago.  I'm pretty sure this was the problem all along! Testing now.

This is fixed in https://github.com/LowellObservatory/DataServants/commit/b2237ef50cdc8b0a7e7f6dd1ec4c1686b32a6b29.

**Comment by astrobokonon** [comment]
Should at least consider warning (loudly, and often) if there is no listener defined.

**Comment by astrobokonon** [comment]
Isn't 100% fixed; looks like it went silent unexpectedly today. The microwave link went down at some point in the afternoon, and while Iago didn't see any interruption in the log it still went silent.

```
2018-08-17 20:46:08,865 INFO     [{'measurement': 'InstrumentTelemetry', 'tags': {'name': 'deveny'}, 'fields': {'H1': 1.08, 'H2': 0.0}}]
2018-08-17 20:46:08,932 INFO     [{'measurement': 'InstrumentTelemetry', 'tags': {'name': 'deveny'}, 'fields': {'T1': -110.06, 'T2': 13.9, 'S1': -109.95, 'S2': 0.0, 'T1S1delta': -0.10999999999999943}}]
2018-08-17 20:47:02,258 INFO     Connection still valid
2018-08-17 20:47:02,258 INFO     Starting a big sleep
2018-08-17 20:57:02,932 INFO     Connection still valid
2018-08-17 20:57:02,932 INFO     Starting a big sleep
2018-08-17 21:07:03,610 INFO     Connection still valid
2018-08-17 21:07:03,610 INFO     Starting a big sleep
```

This happened both on sleeperservice and labmac2, which sucks.

**Comment by astrobokonon** [comment]
Seems like the only foolproof solution is to either implement an actual heartbeat check or to just check joeHeartbeat or whatever. So annoying!!

**Comment by astrobokonon** [comment]
Note that all pings to most hosts were dropped at 20:43:56; we were notified (by email) that the microwave was down by 21:03. Not sure why Iago's log didn't show that the connection was broken at the 20:47:02 status check in the log above!

**Comment by astrobokonon** [comment]
Not closing this just yet, but I think I fixed the heartbeating in 09d6558ca2c496e322654a879a06215b48b98aac. Still needs long term testing, but probably ok to close since now I can see the following in a toy model's DEBUG log:

```
Connection still valid
Starting a big sleep
2018-08-20 13:28:19,885 - stomp.py - DEBUG - Received frame: 'heartbeat', headers={}, body=None
2018-08-20 13:28:19,968 - stomp.py - DEBUG - Sending a heartbeat message at 744852.25036619
2018-08-20 13:28:19,968 - stomp.py - DEBUG - Sending frame: ['\n']
2018-08-20 13:28:24,885 - stomp.py - DEBUG - Received frame: 'heartbeat', headers={}, body=None
2018-08-20 13:28:24,973 - stomp.py - DEBUG - Sending a heartbeat message at 744857.255253805
2018-08-20 13:28:24,973 - stomp.py - DEBUG - Sending frame: ['\n']
Connection still valid
Starting a big sleep
2018-08-20 13:28:29,975 - stomp.py - DEBUG - Sending a heartbeat message at 744862.257570004
2018-08-20 13:28:29,976 - stomp.py - DEBUG - Sending frame: ['\n']
2018-08-20 13:28:32,391 - stomp.py - WARNING - Heartbeat timeout: diff_receive=7.504890832933597, time=744864.672957349, lastrec=744857.168066516
2018-08-20 13:28:32,391 - stomp.py - INFO - Receiver loop ended
2018-08-20 13:28:32,391 - stomp.py - DEBUG - listener <stomp.connect.StompConnection11 object at 0x107938ac8> has no method on_receiver_loop_completed
2018-08-20 13:28:32,391 - stomp.py - DEBUG - listener <ligmos.utils.amq.ParrotSubscriber object at 0x10807d9e8> has no method on_receiver_loop_completed
Connection died! Reestablishing...
Connecting to 10.10.30.137
2018-08-20 13:28:35,276 - stomp.py - INFO - Attempting connection to host 10.10.30.137, port 61613
2018-08-20 13:29:06,324 - stomp.py - WARNING - Could not connect to host 10.10.30.137, port 61613
Traceback (most recent call last):
  File "/Users/rhamilton/anaconda3/lib/python3.6/site-packages/stomp/transport.py", line 716, in attempt_connection
    self.socket = get_socket(host_and_port[0], host_and_port[1], self.__timeout)
  File "/Users/rhamilton/anaconda3/lib/python3.6/site-packages/stomp/backwardsock26.py", line 16, in get_socket
    return socket.create_connection((host, port), timeout)
  File "/Users/rhamilton/anaconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/Users/rhamilton/anaconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
2018-08-20 13:29:06,326 - stomp.py - DEBUG - Sleeping for 0.1 seconds before attempting reconnect
2018-08-20 13:29:06,526 - stomp.py - INFO - Attempting connection to host 10.10.30.137, port 61613
```

**Comment by astrobokonon** [comment]
NOTE: Also removed `keepalive=True` in d6a6584b5938be5a394a01885a83532f4a9158f6. When I put it in the base Connection object (where heartbeats are now) it returned 

```
2018-08-20 13:36:52,933 - stomp.py - INFO - Attempting connection to host 10.10.30.137, port 61613
2018-08-20 13:36:52,935 - stomp.py - ERROR - keepalive: unable to detect any implementation, DISABLED!
2018-08-20 13:36:52,935 - stomp.py - INFO - Established connection to host 10.10.30.137, port 61613
2018-08-20 13:36:52,936 - stomp.py - INFO - Starting receiver loop
```

So I've just cut it out completely for now.

**Comment by astrobokonon** [comment]
For production, it seems like it was important to have a slightly longer timescale for heartbeat reception. This is likely because when I tested things, I was sending heartbeats at 1 second intervals and was sleeping for 1 second intervals in the main loop (sleep(1) up to bigsleep).  This meant I was *probably* blocking some times, and was getting heartbeat timeout errors that then weren't caught until bigsleep was up.

It's probably worth making the main loop tighter by decreasing bigsleep drastically.  But I've for now increased the heartbeat timeout duration (set heart_beat_receive_scale=2.0 rather than 1.5 which is the default) and increased the time between heartbeats. It needs long-term testing to see if it's still fiddly.

**Comment by astrobokonon** [comment]
Another option would be to drastically reduce the small sleep intervals (down to 0.5 seconds?) to block less.

**Comment by astrobokonon** [comment]
Did all of those things mentioned above in https://github.com/LowellObservatory/DataServants/commit/278e8fb755e159f0f00d2f68845dad3e629fc8f8 and testing overnight on both dev machines
