### ISSUE TITLE
Need to handle AuthenticationExceptions and timeouts

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/ligmos#3]
_From @astrobokonon on July 9, 2018 19:21_

2018-07-09 11:53:51 got an auth. exception from paramiko on alfred, unknown cause but it looks like pings to the site spiked at the same time.

_Copied from original issue: LowellObservatory/DataServants#14_

**Comment by astrobokonon** [comment]
It was uncaught, so Alfred stopped ungracefully and all info stopped flowing.  Iago was asleep at the time but continued to get valid InstrumentTelemetry from LMI and DeVeny.  Got a few alerts about no data which clued me in that things were busted.

**Comment by astrobokonon** [comment]
Also note that two hosts had all pings dropped right before the auth. exception...

**Comment by astrobokonon** [comment]
Add to that ConnectionRefusedErrors; this really belongs in https://github.com/LowellObservatory/ligmos so I'm going to try to move it over there (via https://github-issue-mover.appspot.com/)

**Comment by astrobokonon** [comment]
Ok! Now that we're tracking it over here, I can add that this is annoying and should be fixed.  Here.  Because it involves more stuff than just the Auth and timeouts that paramiko sees.

**Comment by astrobokonon** [comment]
Also getting these:

```
2019-05-28 01:48:19,372 INFO     Connection died! Reestablishing...
2019-05-28 01:48:19,372 INFO     Connecting to X
2019-05-28 01:48:19,375 ERROR    Could not connect to host X, port 61613
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/stomp/transport.py", line 734, in attempt_connection
    self.socket = get_socket(host_and_port[0], host_and_port[1], self.__timeout)
  File "/opt/conda/lib/python3.7/site-packages/stomp/backwardsock26.py", line 16, in get_socket
    return socket.create_connection((host, port), timeout)
  File "/opt/conda/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/opt/conda/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2019-05-28 01:48:19,578 ERROR    Could not connect to host X, port 61613
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/stomp/transport.py", line 734, in attempt_connection
    self.socket = get_socket(host_and_port[0], host_and_port[1], self.__timeout)
  File "/opt/conda/lib/python3.7/site-packages/stomp/backwardsock26.py", line 16, in get_socket
    return socket.create_connection((host, port), timeout)
  File "/opt/conda/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/opt/conda/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2019-05-28 01:48:19,780 ERROR    Could not connect to host X, port 61613
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/stomp/transport.py", line 734, in attempt_connection
    self.socket = get_socket(host_and_port[0], host_and_port[1], self.__timeout)
  File "/opt/conda/lib/python3.7/site-packages/stomp/backwardsock26.py", line 16, in get_socket
    return socket.create_connection((host, port), timeout)
  File "/opt/conda/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/opt/conda/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2019-05-28 01:48:20,181 INFO     STOMP.py connection failed!
```

**Comment by astrobokonon** [comment]
Since Alfred is being retired and stripped back, I'm closing this as wontfix especially since the other errors are covered in other issues.
