### ISSUE TITLE
Clean up the configuration parsers

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/ligmos#9]
Seriously I have like 5 different versions scattered about that all do the same thing in a slightly different way.

![NewGlitteringHorsemouse-size_restricted](https://user-images.githubusercontent.com/1168555/59072509-a8716400-8877-11e9-9b30-d9649dd268b4.gif)

This _includes_ stuff in other repositories; there's at least some in [NightShift](https://github.com/LowellObservatory/NightShift/) that I can remember.  I'm _ignoring_ the ones in [Camelot](https://github.com/LowellObservatory/Camelot/) though, since those are fine to be messy and standalone.

**Comment by astrobokonon** [comment]
Main attack list:

https://github.com/LowellObservatory/ligmos/blob/6071cfc724718a9002d6f6550deb845659c5a909/ligmos/utils/confparsers.py#L23

https://github.com/LowellObservatory/ligmos/blob/6071cfc724718a9002d6f6550deb845659c5a909/ligmos/utils/confparsers.py#L88

https://github.com/LowellObservatory/ligmos/blob/6071cfc724718a9002d6f6550deb845659c5a909/ligmos/utils/confparsers.py#L127

https://github.com/LowellObservatory/ligmos/blob/6071cfc724718a9002d6f6550deb845659c5a909/ligmos/utils/confparsers.py#L171

https://github.com/LowellObservatory/ligmos/blob/6071cfc724718a9002d6f6550deb845659c5a909/ligmos/utils/common.py#L161

https://github.com/LowellObservatory/ligmos/blob/6071cfc724718a9002d6f6550deb845659c5a909/ligmos/utils/common.py#L184

https://github.com/LowellObservatory/ligmos/blob/6071cfc724718a9002d6f6550deb845659c5a909/ligmos/utils/common.py#L262

https://github.com/LowellObservatory/NightShift/blob/09722ac35525c334d07ec15b6ce5b9c5f96f4973/nightshift/common/utils.py#L28

https://github.com/LowellObservatory/NightShift/blob/09722ac35525c334d07ec15b6ce5b9c5f96f4973/nightshift/common/utils.py#L54

https://github.com/LowellObservatory/NightShift/blob/09722ac35525c334d07ec15b6ce5b9c5f96f4973/nightshift/common/utils.py#L71

**Comment by astrobokonon** [comment]
Should also back-out the more file-oriented tasks from NightShift utils to ligmos (somewhere).

**Comment by astrobokonon** [comment]
I'm of the increasing opinion that it should all just be torn out and refactored ... everywhere.

![nukeitfromorbit](https://user-images.githubusercontent.com/1168555/59129434-ad8aed80-8921-11e9-8f68-a13df9ec5ff6.gif)

It's just too messy. I'm going to strip it down to just the bare essentials, parsing the configuration files as they are and keeping the simple-minded ```assignConf``` from NightShift that just iterates thru a class and looks for things in the parsed configuration that match.

**Comment by astrobokonon** [comment]
Majority of the refactor is now done, at least on the ligmos side of the house.  Pull request #10 will go online once I have a chance to change and test the rest.  There might be some needed changes on the confOverhauls branch started by c7765a0e23bb4ca8812071f0ecd9f466581d1134 so the PR is still a draft at this point.

**Comment by astrobokonon** [comment]
Merged everything down just now, will deploy and test in situ.

**Comment by astrobokonon** [comment]
I decided to completely nuke all the docker images associated with these and rebuild, so there could be some bugs due to version updates and the like.  But this was much overdue so I'm ok with squashing those as they appear.

**Comment by astrobokonon** [comment]
Seeing some lingering class/config errors in the dataservants, the 'improper config' warning when it's missing keys.  Needs investigation but things are minimally functional.

**Comment by astrobokonon** [comment]
Abu: fine
Alfred: 
```
2019-06-26 20:25:32,119 INFO     Found the following sections in the configuration file:
2019-06-26 20:25:32,119 INFO     database-dct x x1 x2 x3 x4 x5 x6 x7 x8
2019-06-26 20:25:32,119 INFO     Enabled:
2019-06-26 20:25:32,119 INFO     x x1 x2 x3 x4 x5 x7 x8
2019-06-26 20:25:32,119 INFO     Common:
2019-06-26 20:25:32,119 INFO     database-dct
2019-06-26 20:25:32,122 INFO     Found the following sections in the configuration file:
2019-06-26 20:25:32,122 INFO     y y1 extdns-cloudflare ext-google
2019-06-26 20:25:32,122 INFO     Enabled:
2019-06-26 20:25:32,122 INFO     y y1 extdns-cloudflare ext-google
2019-06-26 20:25:32,122 INFO     Improper config; missing configuration key user
2019-06-26 20:25:32,123 INFO     Improper config; missing configuration key password
2019-06-26 20:25:32,123 INFO     Improper config; missing configuration key srcdir
2019-06-26 20:25:32,123 INFO     Improper config; missing configuration key procmon
2019-06-26 20:25:32,123 INFO     Improper config; missing configuration key user
2019-06-26 20:25:32,123 INFO     Improper config; missing configuration key password
2019-06-26 20:25:32,123 INFO     Improper config; missing configuration key srcdir
2019-06-26 20:25:32,124 INFO     Improper config; missing configuration key procmon
2019-06-26 20:25:32,124 INFO     Improper config; missing configuration key user
2019-06-26 20:25:32,124 INFO     Improper config; missing configuration key password
2019-06-26 20:25:32,124 INFO     Improper config; missing configuration key srcdir
2019-06-26 20:25:32,124 INFO     Improper config; missing configuration key procmon
2019-06-26 20:25:32,124 INFO     Improper config; missing configuration key user
2019-06-26 20:25:32,124 INFO     Improper config; missing configuration key password
2019-06-26 20:25:32,125 INFO     Improper config; missing configuration key srcdir
2019-06-26 20:25:32,125 INFO     Improper config; missing configuration key procmon
2019-06-26 20:25:32,125 INFO     Current PID: 6
```

Iago:
```
2019-06-26 20:25:34,281 INFO     Username None in section dctbroker has no password!
2019-06-26 20:25:34,282 INFO     Found the following sections in the configuration file:
2019-06-26 20:25:34,282 INFO     broker-dct database-dct dctbroker
2019-06-26 20:25:34,282 INFO     Enabled:
2019-06-26 20:25:34,282 INFO     dctbroker
2019-06-26 20:25:34,282 INFO     Common:
2019-06-26 20:25:34,282 INFO     database-dct broker-dct
2019-06-26 20:25:34,282 INFO     Improper config; missing configuration key host
2019-06-26 20:25:34,282 INFO     Improper config; missing configuration key port
2019-06-26 20:25:34,282 INFO     Improper config; missing configuration key type
2019-06-26 20:25:34,283 INFO     Improper config; missing configuration key user
2019-06-26 20:25:34,283 INFO     Current PID: 6
```

**Comment by astrobokonon** [comment]
Ugh. NightShift is a complete disaster! Not working. Not sure what went belly up yet.

**Comment by astrobokonon** [comment]
webcams: fine
radar: fine

**Comment by astrobokonon** [comment]
goes:

```
2019-06-26 21:17:23,485 INFO     Parsing road data...
2019-06-26 21:17:23,485 INFO     	Classes: ['Interstate', 'Federal']
2019-06-26 21:17:28,585 INFO     Interstate: 65 found within 7 degrees of center
2019-06-26 21:17:28,586 INFO     Federal: 352 found within 7 degrees of center
2019-06-26 21:17:28,586 INFO     Parsing county data...
2019-06-26 21:17:30,674 INFO     126 counties found within 7 degrees of center
2019-06-26 21:17:30,688 INFO     Starting infinite loop...
2019-06-26 21:17:30,688 INFO     Looking for files!
2019-06-26 21:17:30,790 INFO     Querying:
...
2019-06-26 21:17:36,786 INFO     Reading: ./outputs/goes//raws/20191772013586_C13.nc
2019-06-26 21:17:36,920 INFO     2.989587593880576
2019-06-26 21:17:36,920 INFO     3.5251001155878576
2019-06-26 21:17:36,933 ERROR    Traceback (most recent call last):
2019-06-26 21:17:36,934 ERROR      File "looper_goes16aws.py", line 177, in <module>
2019-06-26 21:17:36,934 ERROR    forceDown=forceDownloads, forceRegen=forceRegenPlot)
2019-06-26 21:17:36,934 ERROR      File "looper_goes16aws.py", line 116, in main
2019-06-26 21:17:36,934 ERROR    forceRegen=forceRegen)
2019-06-26 21:17:36,934 ERROR      File "/home/lig/Codes/NightShift/nightshift/goes/plot.py", line 255, in makePlots
2019-06-26 21:17:36,934 ERROR    pCoeff=pCoeff)
2019-06-26 21:17:36,935 ERROR      File "/home/lig/Codes/NightShift/nightshift/goes/plot.py", line 119, in crop_image
2019-06-26 21:17:36,935 ERROR    'lat_2': clat})
2019-06-26 21:17:36,935 ERROR      File "/opt/conda/lib/python3.7/site-packages/pyresample/geometry.py", line 723, in compute_optimal_bb_area
2019-06-26 21:17:36,935 ERROR    height, width = self._compute_uniform_shape()
2019-06-26 21:17:36,935 ERROR      File "/opt/conda/lib/python3.7/site-packages/pyresample/geometry.py", line 684, in _compute_uniform_shape
2019-06-26 21:17:36,936 ERROR    leftlons = leftlons.where(leftlons.notnull(), drop=True)
2019-06-26 21:17:36,936 ERROR    AttributeError
2019-06-26 21:17:36,936 ERROR    :
2019-06-26 21:17:36,936 ERROR    'numpy.ndarray' object has no attribute 'where'
```

**Comment by astrobokonon** [comment]
goes is fixed by temporarily pinning pyresample to 1.12.1 (current right now is 1.12.3).

**Comment by astrobokonon** [comment]
I think I'm in a good enough place to call this complete and functional.

**Comment by astrobokonon** [comment]
![giphy](https://user-images.githubusercontent.com/1168555/60222757-5c409080-9833-11e9-8a9c-a7657ce57aaa.gif)
